### ISSUE TITLE
Missing error handler on `socket`.

### ISSUE THREAD

**Issue by mikkhait** [Mlgarrido/node-scorm-player#1]
Getting this error when trying to launch content. Thoughts?

```
Initialize sco: e4fb42d7-61cd-41bb-8f69-9ee523dbe85d
Missing error handler on `socket`.
TypeError: Cannot read property 'name' of undefined
    at makeSkinClass (/Users/mkhait/Developer/node-scorm-player/node_modules/mongoskin/lib/utils.js:33:43)
    at Object.<anonymous> (/Users/mkhait/Developer/node-scorm-player/node_modules/mongoskin/lib/grid.js:6:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/mkhait/Developer/node-scorm-player/node_modules/mongoskin/lib/db.js:22:16)
    at Module._compile (module.js:456:26)
```

**Comment by mlgarrido** [comment]
First copy the file config.default.json to config.json with valid MongoDB parameters. The MongoDB database has need one collection called "scorm_data". This project is very very simple, you need modify the code to work properly with your system.
